// Run with Playwright available via NODE_PATH. Optional CHROMIUM_PATH and THREE_URL.
const assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});try{const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(process.env.THREE_URL||'http://localhost:8771/armada-war-three.html');await page.waitForFunction(()=>window.ArmadaThree?.runtime&&window.ArmadaThree?.diagnostics);await page.evaluate(()=>ArmadaThree.runtime.start(22,6,12,42));await page.waitForFunction(()=>{const s=ArmadaThree.runtime.state();return s.forged>=s.total&&Number.isFinite(s.warT0)});await page.waitForTimeout(500);
 const before=await page.evaluate(()=>{const r=ArmadaThree.runtime,s=r.state(),ship=s.ships.find(x=>x.race===22&&!x.hulls);ship.delay=-10;ship.arr=true;ship.grace=false;ship.cool=0;r.select(ship.id,false);r.view('fly');return {id:ship.id,x:ship.x,yaw:ship.yaw}});
 await page.keyboard.down('w');await page.keyboard.down('a');await page.keyboard.down('Space');await page.waitForTimeout(900);await page.keyboard.up('Space');await page.keyboard.up('a');await page.keyboard.up('w');const flown=await page.evaluate(id=>{const s=ArmadaThree.runtime.state(),ship=s.ships[id];return {pilot:s.pilotId,x:ship.x,yaw:ship.yaw,lastFire:ship.lastFire,now:s.now,hud:document.getElementById('cockpitHud').hidden}},before.id);assert.equal(flown.pilot,before.id);assert.notEqual(flown.x,before.x);assert.notEqual(flown.yaw,before.yaw);assert.equal(flown.hud,false);assert.ok(flown.lastFire>0,JSON.stringify(flown));
 await page.keyboard.press('Escape');await page.evaluate(()=>ArmadaThree.runtime.view('top'));assert.equal(await page.evaluate(()=>ArmadaThree.runtime.state().selected),null);await page.waitForTimeout(200);const initial=await page.evaluate(()=>ArmadaThree.diagnostics());assert.ok(initial.triangles>0);assert.equal(initial.renderer,'Three.js 160');
 // Rebuild into an organic battle, then a different fleet. No stale GPU graph.
 for(const [a,b]of [[8,21],[9,7]]){await page.evaluate(([a,b])=>ArmadaThree.runtime.start(a,b,6,71),[a,b]);await page.waitForFunction(()=>{const s=ArmadaThree.runtime.state();return s.forged>=s.total&&Number.isFinite(s.warT0)});await page.waitForFunction(()=>ArmadaThree.diagnostics().systems[1].ships>=10);}
 const final=await page.evaluate(()=>ArmadaThree.diagnostics());assert.ok(final.memory.geometries<initial.memory.geometries+200,JSON.stringify({initial,final}));assert.deepEqual(errors,[]);console.log(JSON.stringify({controls:'passed',regeneration:'passed',initial,final}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
