"""Create the isolated Three runtime from the pinned battle; never edit old pages."""
from pathlib import Path
root=Path(__file__).resolve().parent.parent
text=(root/'armada-war-tribute-new.html').read_text()
start=text.index('\n<script>\n')+10;end=text.rindex('</script>')
code=text[start:end]
code=code.replace('const gl=cvs.getContext("webgl2",{antialias:true,powerPreference:"high-performance"});','const gl=window.ArmadaThree.geometryStore.gl;')
a=code.index('  let SRC=null;',code.index('function ensureWorkers()'))
b=code.index('  const cut=SRC.indexOf(MARK);',a)
code=code[:a]+'  const SRC=window.ArmadaThree.engineSource;\n'+code[b:]
code=code.replace('  requestAnimationFrame(frame);\n  const wall=', '  requestAnimationFrame(frame);\n  if(document.hidden){lastT=nowMs/1000;return;}\n  const wall=')
# Preserve physics/input/camera and DOM updates; remove the raw WebGL render path.
a=code.index('  const m=mat(),eye=[cam.ex,cam.ey,cam.ez];',code.index('function frame(nowMs)'))
b=code.index('  updateCrewPortrait(now);drawFlightHUD(now);',a)
code=code[:a]+'''  let alive=0;
  for(const s of ships){
    if(!s.vao)continue;
    if(!s.dead){if(warT0!==Infinity&&now-warT0>=s.delay)alive++;continue;}
    if(!s.dustT&&now-(s.deadT||0)>12){s.dustT=now;s.dustDur=3.6+combatRandom()*1.4;s.dustNext=now;}
    if(s.dustT){const k=Math.min(1,(now-s.dustT)/s.dustDur);if(now>=(s.dustNext||0)){dustBurst(s.x,s.y,s.z,s.dvx||0,s.dvy||0,s.dvz||0,Math.max(2,Math.round(10*(1-k))),now);s.dustNext=now+.08+k*.12;}if(k>=1){s.vao=null;continue;}}
    s.x+=(s.dvx||0)*dt;s.y+=(s.dvy||0)*dt;s.z+=(s.dvz||0)*dt;
  }
  pinBeams(now);
  window.ArmadaThree.render(threeState());
''' +code[b:]
# Old renderer-only helpers remain dormant for compatibility with stored mesh
# handles. No native GPU API is used by the engine on this page.
insert='''
function threeState(){return {ships,wrecks,boneyard,beams,tracers,plasmas,missiles,mines,dusts,flashes,ionState,worldBodies,starSystem,celes,cam,now:battleTime,warT0,sceneR,palI,selected:sel,pilotId,genId,height:cvs.height,viewportHeight:cvs.height,SLIDE,width:cvs.width,RACE_DEFS,BEAMCOL,watchMode,counts,forged,total};}
window.ArmadaThree.runtime={geometry:window.ArmadaThree.geometryStore.geometry,xPose,xQAA,gunWorld,hullFinish,shipBarrels,barrelFrame,weaponMuzzle,weaponProfile,raceDefs:RACE_DEFS,slide:SLIDE,state:threeState,
 start(a,b,size=150,seed=42){pickMain=[a,b];pickAlly=[-1,-1];perFleet=size;warSeed=seed;document.getElementById('pick').classList.remove('on');startWar(false)},select,view:setWatchView,
 debug: {get ships(){return ships},get battleAI(){return battleAI},step(seconds){for(let i=0;i<Math.round(seconds*30);i++){battleTime+=1/30;simStep(battleTime,1/30)}}}};
'''
code=code.replace('applyPal();resize();makeStars();',insert+'\napplyPal();resize();makeStars();')
(root/'armada-three-engine.js').write_text('// Isolated Three.js port of battle 62d1fd1. Generated by scripts/build-three-port.py.\n'+code.rstrip()+'\n')
html=text[:start-10]+ '\n<script type="module" src="armada-three-main.js"></script>\n</body>\n</html>\n'
html=html.replace('<title>', '<title>Three.js · ',1).replace('ORBITAL YARD — THE TRIBUTE WAR','ORBITAL YARD — THREE.JS',1)
# Retain all existing UI; make the original one-click accessible.
html=html.replace('every fleet we grew up with', '<a href="armada-war-tribute-new.html">original battle ↗</a>',1)
(root/'armada-war-three.html').write_text(html)
