const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {loadBattle}=require('./headless-battle.cjs');
function scene(){const b=loadBattle();b.run(`ships.length=0;for(let i=0;i<8;i++)ships.push({id:i,seed:100+i,race:6,x:(i<4?-1:1)*450,y:0,z:(i%4)*100,yaw:i<4?0:Math.PI,slen:i%4===0?300:25,v:160,side:i<4?0:1,mark:(i+4)%8,arr:true,grace:false,dead:false,vao:{},lastFire:0,hurtT:-100});warT0=0;sel=null;pilotId=null;watchMode='action';actionCamera=null;`);return b;}
const visible=`s=>{const [f,r,u]=camBasis();return cinemaCorners(s,battleTime).every(p=>{const d=V.sub(p,[cam.ex,cam.ey,cam.ez]),z=V.dot(d,f);return z>0&&Math.abs(V.dot(d,u)/z)<Math.tan(.44)&&Math.abs(V.dot(d,r)/z)<Math.tan(.44)*cvs.width/cvs.height;});}`;
test('opening frames both arriving fleets on desktop and portrait screens',()=>{for(const [w,h]of [[1440,900],[390,844]]){const b=scene();const r=b.run(`(()=>{cvs.width=${w};cvs.height=${h};ships.forEach(s=>{s.arr=false;s.grace=true});battleTime=.1;updateActionCamera(.1,.016);return {kind:actionCamera.kind,finite:Object.values(cam).every(Number.isFinite),visible:ships.every(${visible})};})()`);assert.equal(r.kind,'arrival');assert.ok(r.finite&&r.visible,JSON.stringify(r));}});
test('opening introduces each side once even when simulation lags wall time',()=>{const b=scene();const shots=b.run(`(()=>{const out=[];for(let i=0;i<200;i++){updateActionCamera(i*.05,.1);if(out.at(-1)?.index!==actionCamera.index)out.push({index:actionCamera.index,kind:actionCamera.kind,side:ships[actionCamera.subject].side});}return out;})()`);assert.equal(shots[0].kind,'arrival');assert.deepEqual(Array.from(shots.slice(1,3),s=>[s.kind,s.side]),[['formation',0],['formation',1]]);});
test('live engagements produce varied scales, both sides and periodic battlefield views',()=>{const b=scene();const r=b.run(`(()=>{warT0=-100;const kinds=new Set(),sides=new Set(),cuts=[];for(let i=0;i<6000;i++){const now=i/60;ships.forEach(s=>{s.lastFire=now;s.hurtT=now-.5});updateActionCamera(now,1/60);kinds.add(actionCamera.kind);sides.add(ships[actionCamera.subject].side);if(cuts.at(-1)?.index!==actionCamera.index)cuts.push({index:actionCamera.index,time:now});}return {kinds:[...kinds],sides:[...sides],holds:cuts.slice(1).map((s,i)=>s.time-cuts[i].time)};})()`);for(const k of ['chase','duel','capital','top','all'])assert.ok(r.kinds.includes(k),JSON.stringify(r));assert.equal(r.sides.length,2);assert.ok(r.holds.every(n=>n>=3.8),JSON.stringify(r));});
test('director prefers an actual firing pair over an idle flagship',()=>{const b=scene();const r=b.run(`(()=>{warT0=-100;ships.forEach(s=>{s.lastFire=-100;s.x+=s.id===0?50000:0});ships[2].lastFire=20;ships[6].hurtT=20;updateActionCamera(20,.016);return [actionCamera.subject,actionCamera.partner];})()`);assert.deepEqual(Array.from(r).sort((a,b)=>a-b),[2,6]);});
test('chase keeps a fast turning fighter in frame at 30 and 60 fps',()=>{for(const hz of [30,60]){const b=scene();const r=b.run(`(()=>{warT0=-100;ships[2].slen=16;updateActionCamera(20,0);cinemaStart(actionCamera,{kind:'chase',subject:2,partner:6},ships,20);let misses=0,jump=0,lastYaw;for(let i=0;i<${hz*5};i++){const now=20+i/${hz},s=ships[2];s.yaw+=.24/${hz};s.x+=Math.cos(s.yaw)*220/${hz};s.z+=Math.sin(s.yaw)*220/${hz};s.lastFire=now;ships[6].lastFire=now;battleTime=now;updateActionCamera(now,1/${hz});if(!(${visible})(s))misses++;if(lastYaw!=null)jump=Math.max(jump,Math.abs(Math.atan2(Math.sin(cam.yaw-lastYaw),Math.cos(cam.yaw-lastYaw))));lastYaw=cam.yaw;}return {misses,jump,finite:Object.values(cam).every(Number.isFinite)};})()`);assert.ok(r.finite&&r.misses===0&&r.jump<.05,JSON.stringify({hz,...r}));}});
test('duel framing fits both hulls through separation and portrait resize',()=>{const b=scene();const r=b.run(`(()=>{warT0=-100;updateActionCamera(20,0);cinemaStart(actionCamera,{kind:'duel',subject:0,partner:4},ships,20);cvs.width=390;cvs.height=844;let visible=false;for(let i=0;i<180;i++){battleTime=20+i/60;ships[0].lastFire=ships[4].lastFire=battleTime;updateActionCamera(battleTime,1/60);if(i===179)visible=[ships[0],ships[4]].every(${visible});}return {visible,finite:Object.values(cam).every(Number.isFinite)};})()`);assert.ok(r.visible&&r.finite,JSON.stringify(r));});
test('destroyed subject or opponent gets a held payoff before another cut',()=>{for(const id of [2,6]){const b=scene();const r=b.run(`(()=>{warT0=-100;updateActionCamera(20,0);cinemaStart(actionCamera,{kind:'duel',subject:2,partner:6},ships,20);const index=actionCamera.index;ships[${id}].dead=true;ships[${id}].deadT=20;ships[${id}].vao=null;for(let i=0;i<120;i++)updateActionCamera(20+i/60,1/60);const held=actionCamera.index===index;for(let i=120;i<170;i++)updateActionCamera(20+i/60,1/60);return {held,cut:actionCamera.index>index,finite:Object.values(cam).every(Number.isFinite)};})()`);assert.ok(r.held&&r.cut&&r.finite,JSON.stringify(r));}});
test('camera can hold the final explosion with no living ships',()=>{const b=scene();assert.ok(b.run(`(()=>{warT0=-100;updateActionCamera(20,0);cinemaStart(actionCamera,{kind:'chase',subject:2,partner:6},ships,20);ships.forEach(s=>{s.dead=true;s.deadT=20;s.vao=null});for(let i=0;i<200;i++)updateActionCamera(20+i/60,1/60);return Object.values(cam).every(Number.isFinite);})()`));});
test('quiet battle and a lone moving survivor still have a stable camera',()=>{const b=scene();const r=b.run(`(()=>{warT0=-100;ships.length=1;ships[0].slen=30;ships[0].v=160;let error=0;for(let i=0;i<300;i++){ships[0].x+=160/60;updateActionCamera(20+i/60,1/60);const s=ships[0],d=Math.atan2(s.z-cam.ez,s.x-cam.ex)-cam.yaw;if(i>120)error=Math.max(error,Math.abs(Math.atan2(Math.sin(d),Math.cos(d))));}return {error,finite:Object.values(cam).every(Number.isFinite)};})()`);assert.ok(r.finite&&r.error<.1,JSON.stringify(r));});
test('blocked planned angle is replaced before displaying the shot',()=>{const b=scene();assert.ok(b.run(`(()=>{warT0=-100;updateActionCamera(20,0);const shot={kind:'capital',subject:0,partner:4};let p=cinemaStart(actionCamera,shot,ships,20);worldBodies=[{center:p.eye.slice(),radius:140}];p=cinemaStart(actionCamera,shot,ships,20);return !cinemaBlocked(p.eye,p.focus,0,4,ships);})()`));});
test('automatic camera never takes over manual follow or consumes combat randomness',()=>{const b=scene(),c=scene();assert.ok(b.run(`(()=>{sel=0;const before=JSON.stringify(cam);updateWatchCamera(15,.1);return before===JSON.stringify(cam)&&actionCamera===null;})()`));b.run(`sel=null;warT0=-100;for(let i=0;i<900;i++)updateActionCamera(20+i/60,1/60)`);assert.equal(b.run('combatRandom()'),c.run('combatRandom()'));});
test('both rendering engines use exactly the same director',()=>{const block=path=>{const text=fs.readFileSync(path,'utf8');return text.slice(text.indexOf('// The camera observes combat'),text.indexOf('\nfunction updateWatchCamera('));};assert.equal(block('armada-war-tribute-new.html'),block('armada-three-engine.js'));});
test('sister finishes vary deterministically without mutating fleet palettes',()=>{const b=scene();const r=b.run(`(()=>{const a=hullFinish(ships[1]),again=hullFinish(ships[1]),sister=hullFinish(ships[2]);return {same:JSON.stringify(a)===JSON.stringify(again),different:JSON.stringify(a)!==JSON.stringify(sister),finite:[...a.color,...a.trim].every(x=>Number.isFinite(x)&&x>=0&&x<=1)};})()`);assert.ok(r.same&&r.different&&r.finite);});
test('small attack craft use sprint on approach but escort and capitals retain their pace',()=>{const b=scene();const r=b.run(`(()=>{const s={slen:35,spd:100,spdMax:180};return [craftWant(s,0,null,'ATTACK',1200,1),craftWant(s,0,null,'DEFEND',1200,1),craftWant({...s,hulls:10},0,null,'ATTACK',1200,1)];})()`);assert.ok(r[0]>160);assert.ok(r[1]<100);assert.equal(r[2],100);});
test('interiors introduce the same captain and cockpit between exterior shots without taking control',()=>{
 const b=scene();b.run(`window.ArmadaCrew={drawInterior(){}};warT0=-100;`);
 const r=b.run(`(()=>{const shots=[];for(let i=0;i<9000;i++){const now=20+i/60;ships.forEach(s=>s.lastFire=now);updateActionCamera(now,1/60);if(shots.at(-1)?.index!==actionCamera.index)shots.push({index:actionCamera.index,kind:actionCamera.kind,id:actionCamera.subject,clock:actionCamera.clock});}return {shots,sel,pilotId,finite:Object.values(cam).every(Number.isFinite)};})()`);
 const entries=r.shots.filter(s=>s.kind==='captain');assert.ok(entries.length>=2);assert.equal(r.sel,null);assert.equal(r.pilotId,null);assert.ok(r.finite);
 for(const entry of entries){const i=r.shots.indexOf(entry),before=r.shots[i-1],after=r.shots[i+1];assert.equal(before.id,entry.id);assert.ok(['chase','duel','capital'].includes(before.kind));assert.equal(after.kind,'cockpit');assert.equal(after.id,entry.id);assert.ok(after.clock-entry.clock>=3.99);}
});
test('interior camera stays ahead of actual hull bounds and exits when its captain dies',()=>{
 const b=scene();assert.ok(b.run(`(()=>{window.ArmadaCrew={drawInterior(){}};warT0=-100;updateActionCamera(20,0);cinemaStart(actionCamera,{kind:'cockpit',subject:2,partner:6},ships,20);updateActionCamera(20,.016);const s=ships[2],forward=[Math.cos(s.yaw),0,Math.sin(s.yaw)],eye=[cam.ex,cam.ey,cam.ez],clear=cinemaCorners(s,20).every(p=>V.dot(V.sub(eye,p),forward)>0);s.dead=true;s.deadT=20;updateActionCamera(20.1,.1);return clear&&!cinemaInteriorKind(actionCamera.kind)&&pilotId==null&&sel==null;})()`));
});
