const test=require('node:test'),assert=require('node:assert/strict');
const {loadBattle}=require('./headless-battle.cjs');
function scene(){const b=loadBattle();b.run(`ships.length=0;for(let i=0;i<8;i++)ships.push({id:i,seed:100+i,race:6,x:(i<4?-1:1)*1400,y:0,z:(i%4)*180,yaw:i<4?0:Math.PI,slen:i%4===0?300:35,side:i<4?0:1,arr:true,grace:false,dead:false,vao:{},lastFire:0,hurtT:-100});warT0=0;sel=null;pilotId=null;watchMode='action';actionCamera=null;`);return b;}
test('opening frames both fleets before arrivals become eligible targets',()=>{const b=scene();const r=b.run(`(()=>{ships.forEach(s=>{s.arr=false;s.grace=true});updateActionCamera(.1,.016);return {kind:actionCamera.kind,finite:Object.values(cam).every(Number.isFinite),visible:ships.every(s=>{const [f,r,u]=camBasis(),d=[s.x-cam.ex,s.y-cam.ey,s.z-cam.ez],z=V.dot(d,f);return z>0&&Math.abs(V.dot(d,u)/z)<Math.tan(.44)&&Math.abs(V.dot(d,r)/z)<Math.tan(.44)*cvs.width/cvs.height;})};})()`);assert.equal(r.kind,'arrival');assert.ok(r.finite&&r.visible,JSON.stringify(r));});
test('director cuts between chase, distant, overview, capital and top shots',()=>{const b=scene();const kinds=b.run(`(()=>{const kinds=new Set();for(let i=0;i<3600;i++){updateActionCamera(i/60,1/60);kinds.add(actionCamera.kind)}return [...kinds]})()`);for(const k of ['arrival','chase','wide','all','capital','top'])assert.ok(kinds.includes(k),k);});
test('close chase tracks a fast moving fighter, with finite frames after a subject dies',()=>{const b=scene();const r=b.run(`(()=>{warT0=-100;ships.length=1;ships[0].slen=30;ships[0].v=160;let error=0;for(let i=0;i<300;i++){ships[0].x+=160/60;updateActionCamera(20+i/60,1/60);const s=ships[0],d=Math.atan2(s.z-cam.ez,s.x-cam.ex)-cam.yaw;if(i>120)error=Math.max(error,Math.abs(Math.atan2(Math.sin(d),Math.cos(d))));}return {error,finite:Object.values(cam).every(Number.isFinite)};})()`);assert.ok(r.finite&&r.error<.3,JSON.stringify(r));});
test('manual follow and helm remain outside automatic camera control',()=>{const b=scene();assert.ok(b.run(`(()=>{sel=0;const before=JSON.stringify(cam);updateWatchCamera(15,.1);return before===JSON.stringify(cam)&&actionCamera===null;})()`));});
test('sister finishes vary deterministically without mutating fleet palettes',()=>{const b=scene();const r=b.run(`(()=>{const a=hullFinish(ships[1]),again=hullFinish(ships[1]),sister=hullFinish(ships[2]);return {same:JSON.stringify(a)===JSON.stringify(again),different:JSON.stringify(a)!==JSON.stringify(sister),finite:[...a.color,...a.trim].every(x=>Number.isFinite(x)&&x>=0&&x<=1)};})()`);assert.ok(r.same&&r.different&&r.finite);});
test('small attack craft use sprint on approach but escort and capitals retain their pace',()=>{const b=scene();const r=b.run(`(()=>{const s={slen:35,spd:100,spdMax:180};return [craftWant(s,0,null,'ATTACK',1200,1),craftWant(s,0,null,'DEFEND',1200,1),craftWant({...s,hulls:10},0,null,'ATTACK',1200,1)];})()`);assert.ok(r[0]>160);assert.ok(r[1]<100);assert.equal(r[2],100);});
