const test=require('node:test'),assert=require('node:assert/strict');const {loadBattle}=require('./headless-battle.cjs');
function scene(){const b=loadBattle();b.start(5,6,42,12);b.run(`var sd=ships.find(s=>s.race===5&&s.hulls===10);for(const s of ships)s.dead=s!==sd;Object.assign(sd,{x:0,y:0,z:0,yaw:0,yawV:0,roll:0,pitch:0,v:8,vy:0,spd:8,spdMax:9,slen:500,exL:250,exY:30,exZ:100,arr:true,grace:false});function bit(uid,x,y,z,vx=0,vy=0,vz=0){return {uid,x,y,z,vx,vy,vz,yaw:0,extents:[8,8,8],rad:14,t0:0,integ:3,bax:[0,1,0],bang:0,ax:[0,1,0],ang:0};}wrecks=[];`);return b;}
test('full-width debris corridor selects slow debris without issuing evasive helm orders',()=>{const b=scene();assert.ok(b.run(`(()=>{wrecks=[bit(1,400,0,90),bit(2,420,0,260)];debrisPilot(sd,5);prepareTraffic(5);trafficPilot(sd,5);return sd.debrisTarget===1&&!sd.debrisGoal&&!sd.trafficGoal;})()`));});
test('fast incoming debris is left to shields and never induces a swerve',()=>{const b=scene();assert.ok(b.run(`(()=>{wrecks=[bit(1,350,0,0,-150)];debrisPilot(sd,5);prepareTraffic(5);trafficPilot(sd,5);return sd.debrisTarget===null&&!sd.debrisGoal&&!sd.trafficGoal;})()`));});
test('swept shield impact vaporises debris without hull damage, recoil or daughter wrecks',()=>{const b=scene();assert.ok(b.run(`(()=>{const w=bit(1,-500,0,0,-200);w.trafficPrevious=[500,0,0];sd.trafficPrevious=[0,0,0];wrecks=[w];const before=[sd.x,sd.y,sd.z,sd.v,sd.vy,sd.pitch,sd.roll,sd.hp].join();collide(5);return w.shatter&&before===[sd.x,sd.y,sd.z,sd.v,sd.vy,sd.pitch,sd.roll,sd.hp].join()&&debrisQueue.length===0&&flashes.some(f=>f.c===11);})()`));});
test('shield proximity alone does not delete a nearby fragment or an entire large disabled ship',()=>{const b=scene();assert.equal(b.run('destroyerShield(sd,bit(1,400,100,300),5)'),false);assert.equal(b.run('shieldCanClear(sd,{disabled:true,rad:1000})'),false);});
test('destroyer attitude remains level through repeated emergency braking and alternating avoidance goals',()=>{const b=scene();const r=b.run(`(()=>{let pitch=0,roll=0,step=0,previous=0;battleAI.destination=()=>({goal:[2000,0,0],boost:1,mode:'SEARCH',target:-1});for(let i=0;i<360;i++){const now=i/30;sd.v=i%30===0?.01:sd.v;sd.trafficGoal=[sd.x+800,i%60<30?500:-500,sd.z];sd.trafficUntil=now+1;sd.trafficBrake=.08;battleAI.moveCapital(sd,now,1/30);pitch=Math.max(pitch,Math.abs(sd.pitch));roll=Math.max(roll,Math.abs(sd.roll));step=Math.max(step,Math.abs(sd.pitch-previous));previous=sd.pitch;}return {pitch,roll,step,speed:sd.v};})()`);assert.ok(r.pitch<=.025&&r.roll<.001&&r.step<.001);assert.ok(r.speed>=0&&r.speed<=9);});
test('destroyer arrivals and cruising are slow while TIE heroes retain their fighter handling',()=>{const b=scene();assert.ok(b.run(`(()=>{setShipPace(sd);const hero=ships.find(s=>s.hero&&s.race===5);return sd.steadyCapital&&sd.turn<=.025&&sd.spdMax<16&&!hero.steadyCapital&&hero.spd>sd.spd;})()`));});
test('forward debris clearance fires real aligned weapon projectiles',()=>{const b=scene();assert.ok(b.run(`(()=>{sd.guns=[[251,0,0]];sd.turrets=[];sd.lances=[];sd.barrelMounts=null;sd.fireL=null;sd.weaponTracks=new Map();wrecks=[bit(1,400,0,0)];sd.debrisTarget=1;let fired=false;for(let i=0;i<120;i++)fired=fireAtDebris(sd,5+i/30)||fired;return fired&&tracers.some(t=>t.from===sd.id&&t.energy&&t.damage===8);})()`));});

test('render pose preserves tiny gradual pitch changes instead of snapping at the old cutoff',()=>{const b=scene();assert.ok(b.run(`(()=>{sd.pitch=.019;const a=xPose(sd,5);sd.pitch=.021;const b=xPose(sd,5);return a.ang>0&&Math.abs(b.ang-a.ang)<.003;})()`));});
